import ProblemsPage from '../components/ProblemsPage'
// import ReactDataGrid from '@inovua/reactdatagrid-community';
import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    var columns = [
        { key: 'problem_number', name: 'Problem Number', sortable: true, sortDescendingFirst: true }
    ];
    return (
        <>
            <Head>
                <title>ChatGPT Leetcode Bot</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ProblemsPage />
        </>
    )
}
